# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCaption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('illustration', mezzanine.core.fields.FileField(max_length=255, null=True, verbose_name='illustration')),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('caption', mezzanine.core.fields.RichTextField()),
            ],
            options={
                'ordering': ('_order',),
            },
            bases=('pages.page', models.Model),
        ),
        migrations.CreateModel(
            name='HomeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/videos')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MAIN.HomePage')),
            ],
        ),
        migrations.AddField(
            model_name='homecaption',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MAIN.HomePage'),
        ),
    ]
