# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 17:38
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0002_auto_20170208_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='homevideo',
            name='illustration_alt',
            field=mezzanine.core.fields.FileField(max_length=255, null=True, verbose_name='illustration_alt'),
        ),
    ]
