# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0003_homevideo_illustration_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homevideo',
            name='file',
            field=models.FileField(max_length=255, upload_to='illustration_alt'),
        ),
    ]
