# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 18:09
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0004_auto_20170208_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homevideo',
            name='file',
            field=mezzanine.core.fields.FileField(max_length=255),
        ),
    ]
