# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0005_auto_20170208_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='homevideo',
            name='darken_navbar',
            field=models.BooleanField(default=False, help_text="Ajouter un fond sombre \xe0 la navbar pour qu'elle ressorte correctement lorsque le fond de la video est clair", verbose_name='Assombrir navbar'),
        ),
    ]
